#!/bin/sh

set -e

die() {
    echo "Precommit: Encountered errors, exiting ($1)."
    exit "${1:-1}"
}

cd "$(dirname "$(git rev-parse --git-dir)")"
echo "Precommit: Stashing unstaged changes..."
git stash save --keep-index --include-untracked "GoHS presubmit stash ($(date))."

set +e

echo "Precommit: Linting..."
lintLog="$(mktemp)"
hlint src >"$lintLog" 2>&1
result="$?"
if test "$result" -ne 0; then
    echo
    cat "$lintLog"
    rm "$lintLog"
    echo
    echo "Precommit: Lint detected, please clean."
    die "$result"
fi
rm "$lintLog"

echo "Precommit: Checking that the package builds..."
buildLog="$(mktemp)"
cabal build >"$buildLog" 2>&1
result="$?"
if test "$result" -ne 0; then
    echo
    cat "$buildLog"
    rm "$buildLog"
    echo
    echo "Precommit: Failed to build, please fix."
    die "$result"
fi
rm "$buildLog"

echo "Precommit: Running tests..."
testLog="$(mktemp)"
./test.sh >"$testLog" 2>&1
result="$?"
if test "$result" -ne 0; then
    echo
    cat "$testLog"
    rm "$testLog"
    echo
    echo "Precommit: Tests failed, please fix."
    die "$result"
fi
rm "$testLog"

echo "Precommit: Popping stashed changes..."
git stash pop
result="$?"
if test "$result" -ne 0; then
    echo "Precommit: Failed to unstash changes prior to commit."
    die "$result"
fi

echo "Precommit: Success."
exit 0
