#!/bin/bash

# This file is part of Goatee.
#
# Copyright 2014 Bryan Gardiner
#
# Goatee is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Goatee is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Goatee.  If not, see <http://www.gnu.org/licenses/>.

echo "Hlint:"
echo
hlint src
hlintResult=$?

if git --no-pager grep -q '\s\+$'; then
    echo
    echo "Trailing whitespace found:"
    echo
    git --no-pager grep -n --no-color '\s\+$'
    whitespaceResult=1
else
    whitespaceResult=0
fi

if git --no-pager grep -q '	' src; then
    echo
    echo "Tabs found:"
    echo
    git --no-pager grep -n --no-color '	' src
    tabsResult=1
else
    tabsResult=0
fi

if git --no-pager grep -q '.\{101\}'; then
    echo
    echo ">100-char lines found:"
    echo
    git --no-pager grep -n --no-color '.\{101\}'
    longLinesResult=1
else
    longLinesResult=0
fi

# Check that all files contain copyright and license notices.
legalResult=0
while read file; do
    # Only check tracked files.
    if git ls-files --error-unmatch "$file" >/dev/null 2>&1; then
        if ! head -5 "$file" | grep -q Copyright \
            || ! head -20 "$file" | grep -q 'Affero General Public License'; then
            if test $legalResult -eq 0; then
                echo
                echo "Missing or bad copyright/license notices for files:"
                echo
                legalResult=1
            fi
            echo "$file"
        fi
    fi
done < <(find hooks src -type f)
# TODO ^ Rewrite this process substitution in a POSIX-friendly manner.

if test $hlintResult -eq 0 \
    -a $whitespaceResult -eq 0 \
    -a $tabsResult -eq 0 \
    -a $longLinesResult -eq 0 \
    -a $legalResult -eq 0; then
    exit 0
else
    exit 1
fi
