#!/bin/bash

# This file is part of Goatee.
#
# Copyright 2014 Bryan Gardiner
#
# Goatee is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Goatee is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Goatee.  If not, see <http://www.gnu.org/licenses/>.

cd "$(dirname "$(dirname "$(realpath "$0")")")"

srcDirs=`echo src* tests`

echo "HLint:"
echo
hlint $srcDirs
hlintResult=$?

if git --no-pager grep -q '\s\+$'; then
    echo
    echo "Trailing whitespace found:"
    echo
    git --no-pager grep -n --no-color '\s\+$'
    whitespaceResult=1
else
    whitespaceResult=0
fi

tabsResult=0
# Tabs are not allowed anywhere in Haskell files.
if git --no-pager grep -q '	' *.hs $srcDirs; then
    if test $tabsResult -eq 0; then
        echo
        echo "Tabs found:"
        echo
        tabsResult=1
    fi
    git --no-pager grep -n --no-color '	' *.hs $srcDirs
fi
# Tabs shouldn't be used for leading whitespace anywhere.
if git --no-pager grep -q '^	'; then
    if test $tabsResult -eq 0; then
        echo
        echo "Leading tabs found:"
        echo
        tabsResult=1
    fi
    git --no-pager grep -n --no-color '^	'
fi

if git --no-pager grep -q '.\{101\}'; then
    echo
    echo ">100-char lines found:"
    echo
    git --no-pager grep -n --no-color '.\{101\}'
    longLinesResult=1
else
    longLinesResult=0
fi

# Check that all files contain copyright and license notices.
legalResult=0
while read file; do
    # Only check tracked files.
    if git ls-files --error-unmatch "$file" >/dev/null 2>&1; then
        if ! head -5 "$file" | grep -q Copyright \
            || ! head -20 "$file" | grep -q 'Affero General Public License'; then
            if test $legalResult -eq 0; then
                echo
                echo "Missing or bad copyright/license notices for files:"
                echo
                legalResult=1
            fi
            echo "$file"
        fi
    fi
done < <(find hooks $srcDirs -type f)
# TODO ^ Rewrite this process substitution in a POSIX-friendly manner.

# Check that all tracked files are listed in goatee.cabal.
if cabal help sdist |& grep -qe --list-sources; then
    sdistResult=1
    set -e
    sdistDir="$(mktemp -d)"
    set +e
    cabal sdist --list-sources="$sdistDir/sdist-files-raw" >/dev/null
    if ! test -r "$sdistDir/sdist-files-raw"; then
        echo "Failed to list source distribution files."
    else
        sed 's!^\./!!' <"$sdistDir/sdist-files-raw" | sort | uniq >"$sdistDir/sdist-files"
        git ls-files | sort >"$sdistDir/tracked-files"
        if ! cmp "$sdistDir/tracked-files" "$sdistDir/sdist-files" >/dev/null; then
            echo
            echo "Some files are missing from the source distribution."
            echo "Please add them to the Cabal file."
            echo "Diff between expected (tracked) files and actual files:"
            echo
            diff -u "$sdistDir/tracked-files" "$sdistDir/sdist-files"
        else
            sdistResult=0
        fi
    fi
    rm -rf "$sdistDir"
else
    sdistResult=0
fi

if test $hlintResult -eq 0 \
    -a $whitespaceResult -eq 0 \
    -a $tabsResult -eq 0 \
    -a $longLinesResult -eq 0 \
    -a $legalResult -eq 0 \
    -a $sdistResult -eq 0; then
    exit 0
else
    exit 1
fi
