#!/usr/bin/env bash

# This file is part of Goatee.
#
# Copyright 2014 Bryan Gardiner
#
# Goatee is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Goatee is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Goatee.  If not, see <http://www.gnu.org/licenses/>.

# This is the Git pre-commit hook for Goatee development.  It ensures that all
# of the Cabal projects in this repository compile, and pass unit tests and lint
# checks.  It exits with 0 on success and 1 on failure.

set -eu

# We want to make use of aliases.  Unset any aliases that are brought in from
# the environment.
unalias -a
shopt -s expand_aliases

# Git has GIT_DIR set during the execution of hooks, presumably to cache the
# value.  Since we'll be moving around, unset it so that git looks to find the
# correct path.
unset GIT_DIR

declare -r forceVerifyTargetsAll=' goatee goatee-gtk goatee-wx other '
targetIsKnown() {
    [[ $forceVerifyTargetsAll = *\ $1\ * ]]
}

forceVerifyTargets=

usage() {
    cat <<EOF
git-pre-commit - The Goatee Git pre-commit script.

This script runs tests against the state of Goatee in the Git index.  A rough
order of operations are:
1. Stash away unstaged changes.
2. Verify the working tree in chunks called 'targets'.
3. Restore unstaged changes.
4. Exit 0 if all verification passed, non-zero otherwise.

Usage: git-pre-commit [options...]

Options:
    --help
        Displays this help message.

    --verify 'target ...'
    --verify-all
        Forces an explicit verification of specified targets.  The default is
        to verify targets with changes that are staged, plus transitive
        dependencies.

Targets:
   goatee     : The Goatee library.
   goatee-gtk : The Goatee GTK+ UI.
   goatee-wx  : The Goatee wxWidgets UI.
   other      : Miscellaneous files not in a Cabal package.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) usage; exit 0;;
        --verify)
            if [[ $# -eq 1 ]]; then
                echo "$1 requires one argument.  See --help."
                exit 1
            fi
            for target in $2; do
                if ! targetIsKnown "$target"; then
                    echo "Unknown target \"$target\" to verify."
                    exit 1
                fi
            done
            forceVerifyTargets="$forceVerifyTargets $2"
            shift
            ;;
        --verify-all)
            forceVerifyTargets="$forceVerifyTargetsAll"
            ;;
        *) echo "Unknown option: $1."; exit 1;;
    esac
    shift
done

declare -r precommitBuildOpts="-Werror -fno-warn-warnings-deprecations"
declare -r projectDir="$(dirname "$(realpath "$(git rev-parse --git-dir)")")"
declare -r scriptsDir="$(dirname "$(realpath "$0")")"
declare -r unstagedDiff="$(mktemp)"
declare -r allowUnsandboxedInstallFile="$projectDir/allow-unsandboxed-install"

#### Messaging functions

msgPrefix='*'

# Increments the nesting level of messages shown with 'msg' and 'err'.  Call on
# entry to a function.
msgIncDepth() {
    msgPrefix="*$msgPrefix"
}

# Decrements the nesting level of messages shown with 'msg' and 'err'.  Call
# before return from a function.
msgDecDepth() {
    msgPrefix="${msgPrefix#?}"
}

# This is like 'echo', but it prefixes the output with a number of stars
# depending on the nesting level from msgIncDepth/msgDecDepth.
alias msg='echo "$msgPrefix${FUNCNAME:+ $FUNCNAME:}"'

# Like 'msg', but labels the output as an error message.
alias err='echo "$msgPrefix${FUNCNAME:+ $FUNCNAME:} Error:"'

#### Cabal sandbox functions

# Usage: sandboxSupported
#
# Returns 0 if cabal-install supports sandboxes, and non-zero otherwise.
sandboxSupported() {
    cabal help sandbox &>/dev/null
}

# Usage: cabal install $(sandboxInstallFlags) ...
#
# Returns sandbox-appropriate flags that should be used for "cabal
# install"s.
sandboxInstallFlags() {
    if ! sandboxSupported; then
        echo --user
    fi
}

# Usage: sandboxInit
#
# Initializes a precommit sandbox for the current package.  Puts aside an
# existing sandbox, if one exists.  Returns 0 on success, 1 on error.
sandboxInit() {
    msgIncDepth

    if ! sandboxSupported; then
        if [[ -e $allowUnsandboxedInstallFile ]]; then
            msg "Cabal <1.18 is too old to support sandboxes:"
            cabal --version
            msg "Proceeding, as user installs are permitted."
            msgDecDepth
            return 0
        else
            err "The pre-commit script needs to install the Goatee library to verify"
            err "other packages, but Cabal <1.18 is too old to support sandboxes:"
            cabal --version
            err "The pre-commit script can proceed by a user install of the library,"
            err "but won't do so unless you agree to doing a user install by creating"
            err "the following file:"
            err
            err "    $allowUnsandboxedInstallFile"
            msgDecDepth
            return 1
        fi
    fi

    if [[ -e .precommit-sandbox ]]; then
        msg "Old precommit sandbox exists; removing:"
        msg "    $(realpath .precommit-sandbox)"
        rm -r .precommit-sandbox
        if [[ -e cabal.sandbox.config ]] \
            && grep -q '\.precommit-sandbox' cabal.sandbox.config; then
            msg "Also removing cabal.sandbox.config pointing to precommit sandbox."
            rm cabal.sandbox.config
        fi
    fi
    if [[ -e cabal.sandbox.config ]]; then
        mv cabal.sandbox.config{,.non-precommit} || { msgDecDepth; return 1; }
    fi
    cabal sandbox --sandbox=.precommit-sandbox init || { msgDecDepth; return 1; }

    msgDecDepth
}

# Usage: sandboxClean
#
# Cleans the precommit sandbox for the current package (if one exists), and
# restores a set-aside sandbox (if one exists).
sandboxClean() {
    if ! sandboxSupported || ! [[ -e cabal.sandbox.config ]]; then
        return 0
    fi
    msgIncDepth
    if ! grep -q '\.precommit-sandbox' cabal.sandbox.config; then
        err "Precommit: Error: Asked to clean non-precommit sandbox, refusing:"
        msg "    $(realpath cabal.sandbox.config):"
        msg "$(grep -n '\bprefix:' cabal.sandbox.config | sed 's/^/        /')"
    fi
    cabal sandbox delete
    rm -rf .precommit-sandbox
    if [[ -e cabal.sandbox.config.non-precommit ]]; then
        mv cabal.sandbox.config{.non-precommit,}
    fi
    msgDecDepth
}

# verifyPackage packageName (install-lib | no-install-lib) (test | no-test)
#
# Verifies the Cabal package in the named directory by:
# - cleaning;
# - creating a sandbox and installing the 'goatee' library package, if
#   'install-lib' is given as an argument;
# - configuring;
# - building;
# - testing, if 'test' is given as an argument;
# - (cleaning up the sandbox, if one was created).
#
# Returns 0 on success, 1 on error.
verifyPackage() {
    msgIncDepth
    local -r packageName=$1
    local doInstallLib
    local doTest
    local result
    case "$2" in
        install-lib) doInstallLib=1;;
        no-install-lib) doInstallLib=;;
        *) err "Don't know this doInstallLib: \"$2\""; msgDecDepth; return 1;;
    esac
    case "$3" in
        test) doTest=1;;
        no-test) doTest=;;
        *) err "Don't know this doTest: \"$3\""; msgDecDepth; return 1;;
    esac
    echo
    msg "Verifying $packageName."
    cd "$projectDir/$packageName" || { msgDecDepth; return 1; }

    if [[ -n $doInstallLib ]]; then
        msg "Installing goatee library."
        sandboxInit \
            && cabal install $(sandboxInstallFlags) ../goatee; fi \
            && { msg "Cleaning."; cabal clean; } \
            && { msg "Configuring."; cabal configure ${doTest:+--enable-tests}; } \
            && { msg "Building."; cabal build --ghc-options="$precommitBuildOpts"; } \
            && if [[ -n $doTest ]]; then msg "Testing."; cabal test; fi \
            && { msg "Linting."; "$scriptsDir"/lint .; }

    result=$?
    sandboxClean
    if [[ $result = 0 ]]; then
        msg "Package $packageName looks good."
    else
        msg "Package $packageName failed verification."
    fi
    msgDecDepth
    return $result
}

cd "$projectDir"
set +e

if git diff --name-only | grep -q scripts/git-pre-commit \
    && git diff --name-only --cached | grep -q scripts/git-pre-commit; then
    err "Bash doesn't like scripts moving underneath it, so a partial commit to"
    err "scripts/git-pre-commit is incompatible with running the pre-commit"
    err "currently.  Please stash the changes yourself before attempting to"
    err "commit."
    # This could be fixed by doing the initial stash from a separate script
    # before calling this script.  Then /that/ script couldn't have a partial
    # commit, but it would be much smaller.
    exit 1
fi
set -e
git diff --full-index --binary >"$unstagedDiff"
if [[ -s "$unstagedDiff" ]]; then
    msg "Stashing unstaged changes in $unstagedDiff."
    git stash save --keep-index --quiet "Goatee precommit stash ($(date))."
else
    msg "No unstaged changes to stash."
fi
set +e

# Determine what has changed, so that we only verify affected things.
determineTargets() {
    msgIncDepth
    msg "Determining what targets to verify."
    if [[ -n $forceVerifyTargets ]]; then
        msg "Manual targets specified:" $forceVerifyTargets
        forceVerifyTargets=" $forceVerifyTargets "
        [[ $forceVerifyTargets = *\ goatee\ * ]]; verifyLib=$?
        [[ $forceVerifyTargets = *\ goatee-gtk\ * ]]; verifyGtk=$?
        [[ $forceVerifyTargets = *\ goatee-wx\ * ]]; verifyWx=$?
        [[ $forceVerifyTargets = *\ other\ * ]]; verifyOther=$?
    else
        git diff --name-only --cached | grep -qv '^goatee\(\|-gtk\|-wx\)/'; verifyOther=$?
        if [[ $verifyOther -eq 0 ]]; then
            msg "Files changed outside of Cabal packages.  Verifying everything."
            verifyLib=0
            verifyGtk=0
            verifyWx=0
        else
            git diff --name-only --cached | grep -q '^goatee/'; verifyLib=$?
            if [[ $verifyLib -eq 0 ]]; then
                msg "Library changed, forcing verification of other packages."
                verifyGtk=0
                verifyWx=0
            else
                git diff --name-only --cached | grep -q '^goatee-gtk/'; verifyGtk=$?
                git diff --name-only --cached | grep -q '^goatee-wx/'; verifyWx=$?
                if [[ $verifyGtk -eq 0 ]]; then msg "GTK+ UI changed, will verify."; fi
                if [[ $verifyWx -eq 0 ]]; then msg "wxWidgets UI changed, will verify."; fi
            fi
        fi
    fi
    msgDecDepth
}
determineTargets

# Verify the affected targets!
if [[ $verifyLib -eq 0 ]]; then
    verifyPackage goatee no-install-lib test
    resultGoatee=$?
else
    msg "Target goatee is unchanged, skipping verification."
    resultGoatee=0
fi
if [[ $resultGoatee -eq 0 ]]; then
    if [[ $verifyGtk -eq 0 ]]; then
        verifyPackage goatee-gtk install-lib test
        resultGtk=$?
    else
        msg "Target goatee-gtk is unchanged, skipping verification."
        resultGtk=0
    fi
    if [[ $verifyWx -eq 0 ]]; then
        # Verifying the wxWidgets UI is optional and is skipped if wx
        # not installed.  Shouldn't have to install wx to work on
        # Goatee.
        if ghc-pkg latest wx &>/dev/null; then
            verifyPackage goatee-wx install-lib no-test
            resultWx=$?
        else
            msg "Target goatee-wx is missing wx, skipping verification."
            resultWx=0
        fi
    else
        msg "Target goatee-wx is unchanged, skipping verification."
        resultWx=0
    fi
else
    msg "Skipping verification of goatee-gtk and goatee-wx, since goatee failed."
    resultGtk=1
    resultWx=1
fi

if [[ $verifyOther -eq 0 ]]; then
    echo
    msg "Linting miscellaneous files."
    cd "$projectDir"
    "$scriptsDir"/lint "$scriptsDir"
    resultLintOther=$?
else
    msg "Target other is unchanged, skipping verification."
    resultLintOther=0
fi

if [[ -s "$unstagedDiff" ]]; then
    msg "Restoring stashed changes."

    cd "$projectDir"
    git apply --whitespace=nowarn <"$unstagedDiff" &&
    git stash drop &&
    rm "$unstagedDiff"

    resultUnstash=$?
else
    resultUnstash=0
fi

showResult() {
    local -r packageName=$1
    local -r verificationRun=$2
    local -r verificationResult=$3
    local label
    if [[ $verificationRun -ne 0 ]]; then
        label=skip
    elif [[ $verificationResult -eq 0 ]]; then
        label=pass
    else
        label=FAIL
    fi
    msg "  $packageName: $label ($verificationResult)"
}

echo
msg "Results:"
showResult "goatee    " $verifyLib $resultGoatee
showResult "goatee-gtk" $verifyGtk $resultGtk
showResult "goatee-wx " $verifyWx $resultWx
showResult "lint-other" $verifyOther $resultLintOther
showResult "unstash   " $resultUnstash 0

if [[ $resultGoatee = 0 \
    && $resultGtk = 0 \
    && $resultWx = 0 \
    && $resultLintOther = 0 \
    && $resultUnstash = 0 ]]; then
    exit 0
else
    exit 1
fi
